services:
- docker
env:
  global:
  - GCP_PROJECT_ID=devops-eksamen-295808
  - tf_version=0.13.2
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: qsFn9cOaCQP8WEsXBxiGagvBrD4i3yB8YFkzsBiByNjr+p5KbTWCyKiGydB+gc1rPz3/oCaQHijvghiWRr9kjy6hpkduBkMcGpdANk3VZtqeCy6IAt0AtobPFjl6Pj24aGGaMpGF7wjmQsL2j/LKS2Arx1vZI8CwO96WxVy6HihOv3AYYRBddpK7kjvdZ/ItcjxaKxlSoSNvGnRUK05GCHjfUliQmzO9Lyaa/phrFxv5Hs3Fe9QG/8Riv4CBqjJKnt2suTVERBkH6lQPImT10QTajEH+LSzShhREvV2gKDygCqX5Psb1P3JXtN2ey1got+5W4tejOiRvC1kEYT1q9w1qICSUlPuarwNHSSWCAKKNt9FWLwDpPbnEepJExikl/CgP8CE/Rq5sh5XucZtiF2DM7h7zNh0N+gjG80Ly8RfzxlXfC3OcaDHUkG8HA31rZ71xfzr/IK1iFN2JdD8cp8df0xXb+45ZTS6ix+UmHpO7nDbyjWJSuJsTQXqEIPFwGo9N+vd5i5eVLRGQRpygISWeV2d8mF2XtKxCvhStzYimn/cqft7y/3Wmh/e69MeM9yO2KhavJfNFWxglN9Qf1CnV9+1wHxn7JU8spY1uoZDL8c8ksiTPPwn0bwaVYktRK0uSQ79IMSUBjWnmjZ/7PqG8VW/7lHGpVs/xVbu9IxI=
  - secure: Rz97JCUbmbue8UlDvXujtR5se3mEcDWQYVSEaiB098+kvMHGRkPMUdqjsgbd7iHlSIBKlZpoLgZt9Y3OSxDlBwm2V2TwbO2N0s3veDXURvzcYXIsbpiGQgm9G3Rik9VEAZSNuaJ7nLtBvr6BWVSQAHl7V0xo4Ue6dx6dyk3xgGaiAMf5sbqDu/VbsZzwx5+2kj/DNnwPKQFmRRfzjV1BVWbPQvyJJaelJq2bujVyBJQu3he+6u5wmBWdUhVyAdloVVxmdBB2JSf7HVXsfolJkYYhKa5Y8Gmi4+RvaTfCwXvI230/QW5dg9+JE2LKOdAylVOGCqUHVBLzS5V2fWXaS7qMBbVz4758y9ApF2Tj9w7SmVi7A6qJ2D2KI0RR2UrbKuO/kC836VIqeXKDygBZCzirxMUOZQ0NsEXpGAcvbAD0Baf87OPf+ZROc8BxIvL6+TVCZLjJq95i0R5UQBfSbkvAGBt4n9ew7PPlNBY84G4eKcCE8Y1v77S5Vkaw2dcEYB2IjHg+qY0G0RJq6ZB0k55WhnXA5yaKmI46v6vIGKx12Apm4WtwHuLqK1Oi65vIP1Bfaie+k8c0OGaS8qg33MK02gL+oX31cvqVLsH6rhRuMiqj4wNLxeb7p1ZWjCBHw/4C6FYNOEyVOgj+Zym9xDbftl6bhfiKzS6K4GZVtcs=
  - secure: VrsQwabmy0prccx4D2Mr79S58g6Mgf62vlAE81CXRFfkwyuc+lc2ZDvKfzKlcIFhlWBFS10cij8cO7ug46Kk3rwQLefWM4uIfpPbPMkULdLR2zKuMvPQZFhd5avSssqnxgl3PqLfpdm8a0r9jvwFBceYRF5yGMaWMlS870Q+eQioYN1ZOUdBz2kpE2rvTmIsUwYRdc69sfBMnWEiP/cJGAZNiQl4sZ3IN2OvRRUmURIjK2JmICeUaBFnMUMhMcsyGkGumZ4M6TTf3+VtjVm44DgHydGNhFkUHk+SAj0HhNne4MlDmUwEqEDhyEvYGaVpVGvQchL7FzujROdQiCd1teRbiSaEVOQn9LHAPQdGS7xaEG00kG6O0HBb7QfHSM6KU9MtaEfLVeVadLlcF7Z4uA4xj5y1x8br6XHKe+ItFSZlRG6Jfqt+63eniEjz9y40ToLJPL/xMRCigxGidFWYXvjbwylHp61qqZcgXuJt5IKQYUe6OVEU5BtJfY22aKHMF2bl+PMjBE0YmIB9RmTMiSK5ziu3mQaPvWAzlk5xrp2NCUjrEbdvC9O3urlA5ogksd+qyCSACy3TbNKvbAjPNDlX6L3uvoKtlgGLoq4drRUzGIFAnAG7F/9T4tTWx2GUPepcWWw0uZLESVyD7SR+Jw0kswclp6+ufMlcZRctJQ4=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_08046dc9db46_key -iv $encrypted_08046dc9db46_iv
  -in GCP-key.json.enc -out GCP-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=GCP-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./GCP-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
