services:
- docker
env:
  global:
  - GCP_PROJECT_ID=devops-eksamen-295808
  - tf_version=0.13.2
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: lUBxKe0VZ1C9PUKdBJ0f2NV67ioDcdzzHSlvQp0E7+YSN/EZRb/omZjoiRX8xLBQT1sNwAgbbamtIHm6MfoEuirz8lKS4ogW6tQGlqKpRoylN7k8lnJF7U2iRTOEx9+AlgJ34oVob1ms54RSYxIpkHKNzs46eqDfWniFPrS/Xmxd6HaA48USIHyHHyDWrpoV0rdygBXZyN+mgl4Rr+4NfiGX5D/sTTIG/fNdR2uW3FdpTZimeidQK8FTlpzBn1OUd2g20mO+yca28QNHAGOOXAdtleL5t5s2ib7nwRN8IZ5nwrjnFbcR0e0HJ4JMIBiaScutiEnkh/o/bEzeYPvwofk5xHrFyoYhE+1omZtpE1DJ3PakWVTbQsBRM/Gt0RFof6pttHI2uzSU0Rf5gP5c0uq1EU6l9imMwfGXMt3uETj/hE903eDo4iZx1s3BdpH/eXpV1dAtG5Cny5Q1iNgoMk7mQSa08dcjE/C0vXFgo2OoarB1iAGl2xO6Hb7xTnGndygmoBIPeVJGTddooZoXjRgoQPr3JlQajBWZWEsnXL1t6invsYD2w7u2kNvUqJZD7vjnC5PAH3AgK8H92s1em7mQWDTG66jv7KL7ZKGRG1qvXh3JDAh6ZpBQl3DyrS+rEhg6IPlO1oAjI1X+7P/92Z4zfpCJ3ghhIoImqPtM/GY=
  - secure: oHsjNDsfW1iZX9uLCOY44x6jouNR/Z0Ji4DnHqQE4wLezPXXtEkzmLaVO+vjPIKIqHG+q6IwwE/H+YBq5XSJJTLbi7onH1r6pJr+LncT79T9Jzg7ZoibGjTZlr+Tt8LTasMjA1uhineOPMv8zz/YcdhqWLsdEhW+uOWVkt93PXpBeDwgJ1YSEdCBS6yFM9KyjqGcEDH9XWq1fl5hrmS826GRfnXI0mfy7IA5uICh3XGlJmGkRYfYgOPFcR0Lr7KOZwPNBkSPJD10zSGYnw7fL+vB+wGQJRBtL6uJOypebfbKvSiNVcY91WGHTHsNBnymX9cfOFx2tN+6ohX+X0a5M6jFMByD2hqkLZECaD54X6Ymd3DCvIAfTZOEicDbXqo63OWh/QylmRU64U73Ggm9aTmM6Nde3CgaUuJe6wTsnaWkKZ4/32ZpdHQbT8tjvVjhbhi38oMLVS/iokPuZn9fEDQNDkmJdoi4Lxp+/QcNEM9OtJCDRxkEoWgpzwcuKMr2GTRvb0P2A640vgKaPg+RcIxr2AFfYTm76g2OPAgtoDSDUWilDQStbv0xd5VPHDo0CS8SlRm1EwOri/0bDqph8rhqsOQz30CoxZvO9qh/PFyHjnW502/dSD1npEu0AMycI5CuEW7N7MtEiqEnEVax2/3k51QgwcmHgfEkMKe3t44=
  - secure: naHoNIy68GtD+XoIEloRFW5SRxq1tNTXoYernLnF1iudUqKgQcMUQF4rXpubPK7L6WMGSmWbp+DpNygiXOZ8jL9sAEYrv9seuuo/YiUE1QPq1KShMdu9amrJAOsK0U6xfV2s4U/VZea4KTAMoC4/jKqZ1Nl4Ac4x2v/KMVGhExEf2bOx0/lhGaCUYCeE4kMlF/Ivo0deXnB91mFXs0MCLVuBwavYCt+WQnYwY4yRsVDl2Uqsxi15whrxacwqpg5c127rdojR4QF11PgLgRW/ZOcGaQNuP/TIuSN2xCWJTKW4lvTRUTLBI4nT8+6mGfqK7mUzplh7Sc/lL2x2d1aJ3iujYn/RqOGGWfusEcVA2c7WmWDRSgOeoYfS+kKKIN+2LBmsSdRv5rtepn5PlCl7tOUplMjoQ2i2+s+INA/UMJY8J58jLlOt1sdby3qrnG8sVDEVFhoZMAkkdmvxvtNO2TAj5Xfgrgvlt46284yU59T5L8NQfnxKtrAzPLg+f8U068dDh3fOxwsVzcI1FlDqjltbac0Gp4ETglCdFnEWM+DEjA+/vQl2gkTmF4qY1HSk1Z9Zfk8gn3mA4gPPpMuK9dkXJyPKMspudLzxr0spq9J/6YQOkxJ9bfC2qeRCPinjKarguFYp+oz8Lvi1e2TCQf0TOnpax4uY9K1YoQ3fbew=
  - secure: Q3WCBXA3GP0D++iJmMQQ+wkyQA5FAGxd50sFtH45w7048mtP6jIg6bv0ZQPeL5PPoDVg9/JjELzYxcwv0J0zuleLO8L3XxJ7i1rW0Zf4E9l20kaO9LMhbT4e0/BqhXJeYNpuhhnWP9EIHY8Ez9ukY5/PTLYtE8lU4/hWQCjKrUomxVQB9AD1C1P1pZi/wgH7W+sWOezpJbr4BjjfFenhikudWo6M68sQoWJCkEP6o6sDQs7O283oWYBXmM6JpqcH742GVYEmCJaZrX7Micye++KUuSh0qNgu9xLs3W19ow+Ll7LbtkyY0wTse76g/6KlIMoEz32UKC94XX+3Clc1S76B2AM9NEr/5oHsT/E/P3cwwl7YG7jBrAVmvOO4Io6Soe/fYDXQpVDkCqzLuZSKz9EABhuKrKgrYbpFmTmiUVDPv903nskascEE8cUzJbcp/2F/c/99lF2iCIhDRhnPTgugC5YEBkcXhxFVAdVpyG6ylXBR+7FKv+LMmtjV4VDgtpgold18glTEUcLrftsAprCE/P3RTTWwhICfEO41efNP5wRMDtvJ1t2Jgjy5OFT/dkBjs0RhamZU7LPQ4eF59BedYy5mA6Snv6O8VW/J7V8Yvc19PC73dmP9RPzoui34RvQ3JsujO02xjrtfnkT40hpVnap61FPlhRCYcQkq6bI=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_08046dc9db46_key -iv $encrypted_08046dc9db46_iv
  -in GCP-key.json.enc -out GCP-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=GCP-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./GCP-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export tf_var_logz_token=$logz-token
  export tf_var_logz_url=$logz-url
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
